version: '3.8'

services:
  micro_backend:
    build: ../../backend
    container_name: micro_backend
    command: java -jar ./app.jar
    environment:
#      - PORT=8081
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db_postgres_micro/testdb_kh
#      - JS_URL=http://localhost
    ports:
      - "8080:8080"
    depends_on:
      - db_postgres_micro

  micro_frontend:
    build: ../../frontend
    container_name: micro_frontend
    ports:
      - "8081:8081"

  db_postgres_micro:
    image: postgres:latest
    container_name: db_postgres_micro
    ports:
      - "5433:5432"
    volumes:
      - db_data_micro:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb_kh
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root

volumes:
  db_data_micro:
